# Generated by Django 5.2.4 on 2025-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='posts/covers/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='posts/banners/')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('running_time', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
