# Generated by Django 5.2.4 on 2025-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_rating',
            field=models.CharField(blank=True, choices=[('+7', '+7'), ('+12', '+12'), ('+15', '+15'), ('+16', '+16'), ('+18', '+18')], default='+16', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quality',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('HD', 'HD'), ('FHD', 'Full HD'), ('4K', '4K')], default='HD', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='امتیاز بین 0 تا 10', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='running_time',
            field=models.IntegerField(blank=True, help_text='مدت زمان به دقیقه', null=True),
        ),
    ]
