# Generated by Django 5.2.4 on 2025-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_age_rating_post_quality_post_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Rating between 0 and 10', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='running_time',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
