# Generated by Django 5.2.4 on 2025-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
