# Generated by Django 5.2.4 on 2025-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='actors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
