# Generated by Django 5.2.4 on 2025-10-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_comment_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='mymodel',
            new_name='my_model',
        ),
    ]
